### ISSUE TITLE
Invalid HTML attribute value

### ISSUE THREAD

**Issue by mudrd8mz** [SVIeSolutions/moodle-block_via#5]
I guess that instead of the `new` value of the target attribute in the link `<a target="new">`, you probably wanted to have `_blank`.

**Comment by mudrd8mz** [comment]
https://github.com/SVIeSolutions/moodle-block_via/blob/fdb0e5200b8753059123847401b3882fa65584f5/block_via.php#L104

**Comment by SVIeSolutions** [comment]
These have been modified in version 2016042006 added today 05/12/2016.
Thank you!
