### ISSUE TITLE
What is the reasoning for the applicable_formats?

### ISSUE THREAD

**Issue by mudrd8mz** [SVIeSolutions/moodle-block_via#6]
Currently the block declares following as applicable formats:
```
return array('all' => true, 'mod' => false, 'my' => false, 'admin' => false, 'tag' => false);
```
But then other parts of the code expect that the block is used in a course (it uses the global $COURSE) and checks the `mod/via:view` capability in it. To me, it would feel more intuitive if the block could be used on the course page and eventually on any page inside a course (such as on modules' pages).

What was the reasoning for the current value? I would expect something like `array('course-view' => true, 'mod' => true)` unless I am missing something.

**Comment by SVIeSolutions** [comment]
These have been modified in version 2016042006 added today 05/12/2016.
Thank you for the suggestion!
